window.TAROTEAME_CONFIG = {
  SUPABASE_URL: "https://ozbbgfxixbgffxnhqpzh.supabase.co",
  SUPABASE_PUBLISHABLE_KEY: "sb_publishable_Xag7GClzJc37vg2DQXhBVA_QfU0NUyd"
VAPID_PUBLIC_KEY: BALCKNjHMWSNEaNlvAXjnfzZPG3BXgMDEw9cQbFsGWw6OxYoLmDYtKWCBOPVN8vAg3VTu6gX8XZcFSC-x1nc12Y
};
